/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BolsillosRouteImport } from './routes/bolsillos'
import { Route as CategoriasRouteImport } from './routes/categorias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsillosRoute = BolsillosRouteImport.update({
  id: '/bolsillos',
  path: '/bolsillos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bolsillos': typeof BolsillosRoute
  '/categorias': typeof CategoriasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolsillos': typeof BolsillosRoute
  '/categorias': typeof CategoriasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bolsillos': typeof BolsillosRoute
  '/categorias': typeof CategoriasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bolsillos' | '/categorias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bolsillos' | '/categorias'
  id: '__root__' | '/' | '/bolsillos' | '/categorias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BolsillosRoute: typeof BolsillosRoute
  CategoriasRoute: typeof CategoriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsillos': {
      id: '/bolsillos'
      path: '/bolsillos'
      fullPath: '/bolsillos'
      preLoaderRoute: typeof BolsillosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BolsillosRoute: BolsillosRoute,
  CategoriasRoute: CategoriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
